### ISSUE TITLE
how to run this code?

### ISSUE THREAD

**Issue by peng666** [Computational-Plant-Science/pycyapi#6]
I always have the following problems:
ModuleNotFoundError: No module named 'irods'

**Comment by peng666** [comment]
I have a problem now. Does anyone know how to solve it？

(base) pang@pang:/home/software$ ils
ERROR: lsUtil: srcPath /iplant/home/anonymous does not exist or user lacks access permission

**Comment by wpbonelli** [comment]
hi @peng666, I've added basic usage info to the README. you can also look at the contents of the `plantit_cli/tests`. please note however that this project is rapidly evolving and should not be considered stable at this time. IRODS integration is in development

**Comment by wpbonelli** [comment]
@peng666 closing this for housekeeping, but feel free to reach out if you have questions
