### ISSUE TITLE
Protect input data from modification during runs?

### ISSUE THREAD

**Issue by wpbonelli** [Computational-Plant-Science/pycyapi#8]
There is currently no way to temporarily lock user-owned files or directories via the Terrain API. We could copy input data to a hidden folder, but this may not be immune to the same kind of race conditions we want to avoid (although an internal copy will likely complete much more quickly than a download over the wire, and doing so at PlantIT submission time would preclude accidental modification while jobs are pending on a cluster queue). Copying to a hidden folder may add runtime on our end and resource overhead on CyVerse's end, especially if the data are large.

Maybe we could make this configurable per user? They could decide whether the tradeoff is worth it for their use case.

**Comment by koalaspirit** [comment]
Or simply move the data. No storage overhead for CyVerse and should be fast as only the paths is changed compared to copying.

Sent from my iPhone

On Nov 25, 2020, at 7:07 PM, w-bonelli <notifications@github.com> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


There is currently no way to temporarily lock user-owned files or directories via the Terrain API. We could copy input data to a hidden folder, but this may not be immune to the same kind of race conditions we want to avoid (although an internal copy will likely complete much more quickly than a download over the wire). Copying to a hidden folder may add runtime on our end and resource overhead on CyVerse's end, especially if the data are large.

We could make this configurable per user? They could decide whether the tradeoff is worth it for their use case.

**Comment by wpbonelli** [comment]
Addressed by #18
